// SceneSchema.js — GENERATED by tools/manifest.mjs — do not edit by hand.
// Machine-readable scene contract for AI agents and validators: constants with editor
// ranges and mode options, LOCATION_OBJECTS / UI_LAYOUT record fields, the Scene API
// surface (js/SceneAPI.js). Canon: js/Constants.js + _utils/editor/schema.js.
/** @satisfies {Record<string, any>} */
const SCENE_SCHEMA = {
    "kit": "ArcEngine",
    "schemaVersion": 1,
    "gameVersion": "1.0.0",
    "engine": "PlayCanvas 2 (libs/playcanvas.min.js, WebGL2)",
    "coordinates": {
        "map": "x right, y down, height up, px; right-handed tradition",
        "engineWorld": "mirror of the map on X: pc(-x, h, y); rotations via World3D.rotQuat/eulerFromQuat"
    },
    "constants": [
        {
            "group": "camera",
            "name": "CAMERA_FOV_DEG",
            "min": 20,
            "max": 100,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Field of view (°)",
            "value": 52
        },
        {
            "group": "camera",
            "name": "CAMERA_AZIMUTH_DEG",
            "min": -180,
            "max": 180,
            "step": 5,
            "kind": "number",
            "options": null,
            "label": "Heading (°)",
            "value": -90
        },
        {
            "group": "camera",
            "name": "CAMERA_PITCH_DEG",
            "min": 20,
            "max": 90,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Pitch (°)",
            "value": 55
        },
        {
            "group": "camera",
            "name": "CAMERA_ZOOM",
            "min": 0.2,
            "max": 4,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Start zoom: desktop",
            "value": 0.62
        },
        {
            "group": "camera",
            "name": "CAMERA_ZOOM_MOBILE",
            "min": 0.2,
            "max": 4,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Start zoom: phones",
            "value": 0.5
        },
        {
            "group": "camera",
            "name": "CAMERA_ZOOM_MIN",
            "min": 0.1,
            "max": 4,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Zoom: farthest",
            "value": 0.4
        },
        {
            "group": "camera",
            "name": "CAMERA_ZOOM_MAX",
            "min": 0.2,
            "max": 8,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Zoom: closest",
            "value": 1.7
        },
        {
            "group": "camera",
            "name": "CAMERA_ZOOM_WHEEL_STEP",
            "min": 0.02,
            "max": 0.5,
            "step": 0.01,
            "kind": "number",
            "options": null,
            "label": "Wheel step (fraction)",
            "value": 0.12
        },
        {
            "group": "camera",
            "name": "CAMERA_ZOOM_LERP",
            "min": 0.02,
            "max": 1,
            "step": 0.02,
            "kind": "number",
            "options": null,
            "label": "Zoom smoothing",
            "value": 0.18
        },
        {
            "group": "camera",
            "name": "CAMERA_FOLLOW_LERP",
            "min": 0.01,
            "max": 1,
            "step": 0.01,
            "kind": "number",
            "options": null,
            "label": "Follow smoothing",
            "value": 0.11
        },
        {
            "group": "camera",
            "name": "CAMERA_FLY_SPEED",
            "min": 100,
            "max": 3000,
            "step": 50,
            "kind": "number",
            "options": null,
            "label": "Flight speed (screen px/s)",
            "value": 900
        },
        {
            "group": "camera",
            "name": "CAMERA_LIMITS",
            "min": null,
            "max": null,
            "step": null,
            "kind": "select",
            "options": [
                {
                    "value": 0,
                    "label": "no"
                },
                {
                    "value": 1,
                    "label": "yes"
                }
            ],
            "label": "Game camera limits",
            "value": 0
        },
        {
            "group": "camera",
            "name": "CAMERA_LIFT_MAX",
            "min": 0,
            "max": 3000,
            "step": 50,
            "kind": "number",
            "options": null,
            "label": "Limits: flight ceiling (px)",
            "value": 600
        },
        {
            "group": "camera",
            "name": "CAMERA_ORBIT",
            "min": null,
            "max": null,
            "step": null,
            "kind": "select",
            "options": [
                {
                    "value": 0,
                    "label": "off — heading fixed"
                },
                {
                    "value": 1,
                    "label": "RMB rotates"
                }
            ],
            "label": "Player rotation",
            "value": 1
        },
        {
            "group": "camera",
            "name": "CAMERA_ORBIT_DEG_PER_PX",
            "min": 0.05,
            "max": 1,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Rotation speed (°/px)",
            "value": 0.3
        },
        {
            "group": "camera",
            "name": "CAMERA_ORBIT_PITCH_MIN_DEG",
            "min": 5,
            "max": 89,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Limits: lowest pitch (°)",
            "value": 35
        },
        {
            "group": "camera",
            "name": "CAMERA_ORBIT_PITCH_MAX_DEG",
            "min": 20,
            "max": 89,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Limits: highest pitch (°)",
            "value": 88
        },
        {
            "group": "toon",
            "name": "WORLD3D_TOON",
            "min": null,
            "max": null,
            "step": null,
            "kind": "select",
            "options": [
                {
                    "value": 0,
                    "label": "smooth"
                },
                {
                    "value": 1,
                    "label": "toon (bands)"
                }
            ],
            "label": "Shading",
            "value": 1
        },
        {
            "group": "toon",
            "name": "WORLD3D_TOON_BANDS",
            "min": 2,
            "max": 6,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Light bands",
            "value": 4
        },
        {
            "group": "toon",
            "name": "WORLD3D_TOON_SOFT",
            "min": 0,
            "max": 0.5,
            "step": 0.01,
            "kind": "number",
            "options": null,
            "label": "Band edge softness",
            "value": 0.03
        },
        {
            "group": "toon",
            "name": "WORLD3D_TOON_LOW",
            "min": 0,
            "max": 0.9,
            "step": 0.01,
            "kind": "number",
            "options": null,
            "label": "Darkest band",
            "value": 0.5
        },
        {
            "group": "toon",
            "name": "WORLD3D_TOON_GROUND",
            "min": null,
            "max": null,
            "step": null,
            "kind": "select",
            "options": [
                {
                    "value": 0,
                    "label": "no"
                },
                {
                    "value": 1,
                    "label": "yes"
                }
            ],
            "label": "Bands on the ground",
            "value": 1
        },
        {
            "group": "toon",
            "name": "WORLD3D_TOON_SPEC",
            "min": 0,
            "max": 3,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Specular spot",
            "value": 0.22
        },
        {
            "group": "toon",
            "name": "WORLD3D_TOON_SPEC_SIZE",
            "min": 0.01,
            "max": 0.4,
            "step": 0.005,
            "kind": "number",
            "options": null,
            "label": "Specular threshold",
            "value": 0.075
        },
        {
            "group": "toon",
            "name": "WORLD3D_TOON_RIM",
            "min": 0,
            "max": 1,
            "step": 0.02,
            "kind": "number",
            "options": null,
            "label": "Rim light",
            "value": 0.24
        },
        {
            "group": "toon",
            "name": "WORLD3D_TOON_RIM_WIDTH",
            "min": 0.05,
            "max": 0.9,
            "step": 0.01,
            "kind": "number",
            "options": null,
            "label": "Rim width",
            "value": 0.26
        },
        {
            "group": "ink",
            "name": "WORLD3D_TOON_OUTLINE",
            "min": null,
            "max": null,
            "step": null,
            "kind": "select",
            "options": [
                {
                    "value": 0,
                    "label": "off"
                },
                {
                    "value": 1,
                    "label": "main objects"
                },
                {
                    "value": 2,
                    "label": "main + environment"
                }
            ],
            "label": "Silhouette outline",
            "value": 0
        },
        {
            "group": "ink",
            "name": "WORLD3D_TOON_OUTLINE_ACTOR_WIDTH",
            "min": 0,
            "max": 12,
            "step": 0.5,
            "kind": "number",
            "options": null,
            "label": "Outline width: main (screen px)",
            "value": 1.5
        },
        {
            "group": "ink",
            "name": "WORLD3D_TOON_OUTLINE_PROP_WIDTH",
            "min": 0,
            "max": 12,
            "step": 0.5,
            "kind": "number",
            "options": null,
            "label": "Outline width: environment (screen px)",
            "value": 1
        },
        {
            "group": "ink",
            "name": "WORLD3D_TOON_INK",
            "min": null,
            "max": null,
            "step": null,
            "kind": "select",
            "options": [
                {
                    "value": 0,
                    "label": "off"
                },
                {
                    "value": 1,
                    "label": "main objects"
                },
                {
                    "value": 2,
                    "label": "main + environment"
                }
            ],
            "label": "Edge lines",
            "value": 2
        },
        {
            "group": "ink",
            "name": "WORLD3D_TOON_INK_WIDTH",
            "min": 5,
            "max": 400,
            "step": 5,
            "kind": "number",
            "options": null,
            "label": "Edge line width",
            "value": 22
        },
        {
            "group": "ink",
            "name": "WORLD3D_TOON_INK_COLOR",
            "min": null,
            "max": null,
            "step": null,
            "kind": "color",
            "options": null,
            "label": "Ink color",
            "value": 1709842
        },
        {
            "group": "ink",
            "name": "WORLD3D_TOON_INK_ANGLE",
            "min": 5,
            "max": 89,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Crease threshold (°)",
            "value": 42
        },
        {
            "group": "sun",
            "name": "WORLD3D_SUN_AZIMUTH_DEG",
            "min": 0,
            "max": 359,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Sun azimuth (°)",
            "value": 38
        },
        {
            "group": "sun",
            "name": "WORLD3D_SUN_ELEVATION_DEG",
            "min": 10,
            "max": 85,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Sun elevation (°)",
            "value": 44
        },
        {
            "group": "sun",
            "name": "WORLD3D_SUN_INTENSITY",
            "min": 0,
            "max": 2,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Sun intensity",
            "value": 0.82
        },
        {
            "group": "sun",
            "name": "WORLD3D_SUN_COLOR",
            "min": null,
            "max": null,
            "step": null,
            "kind": "color",
            "options": null,
            "label": "Sun color",
            "value": 16772551
        },
        {
            "group": "sun",
            "name": "WORLD3D_SKYLIGHT_INTENSITY",
            "min": 0,
            "max": 1.5,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Sky light",
            "value": 0.44
        },
        {
            "group": "sun",
            "name": "WORLD3D_SKYLIGHT_COLOR",
            "min": null,
            "max": null,
            "step": null,
            "kind": "color",
            "options": null,
            "label": "Sky light color",
            "value": 11655415
        },
        {
            "group": "sun",
            "name": "WORLD3D_GROUNDLIGHT_COLOR",
            "min": null,
            "max": null,
            "step": null,
            "kind": "color",
            "options": null,
            "label": "Ground bounce color",
            "value": 12765101
        },
        {
            "group": "shadow",
            "name": "WORLD3D_SHADOW_COLOR",
            "min": null,
            "max": null,
            "step": null,
            "kind": "color",
            "options": null,
            "label": "Shadow color",
            "value": 1194570
        },
        {
            "group": "shadow",
            "name": "WORLD3D_SHADOW_STRENGTH",
            "min": 0,
            "max": 1,
            "step": 0.02,
            "kind": "number",
            "options": null,
            "label": "Shadow strength",
            "value": 0.5
        },
        {
            "group": "shadow",
            "name": "WORLD3D_SHADOW_SOFT",
            "min": null,
            "max": null,
            "step": null,
            "kind": "select",
            "options": [
                {
                    "value": 0,
                    "label": "hard"
                },
                {
                    "value": 1,
                    "label": "PCF low"
                },
                {
                    "value": 2,
                    "label": "PCF medium"
                },
                {
                    "value": 3,
                    "label": "PCF high"
                }
            ],
            "label": "Shadow edge",
            "value": 2
        },
        {
            "group": "shadow",
            "name": "WORLD3D_SHADOW_MAP",
            "min": 512,
            "max": 4096,
            "step": 512,
            "kind": "number",
            "options": null,
            "label": "Shadow map (px)",
            "value": 1024
        },
        {
            "group": "shadow",
            "name": "WORLD3D_SHADOW_RADIUS",
            "min": 300,
            "max": 1600,
            "step": 20,
            "kind": "number",
            "options": null,
            "label": "Shadow frame (px)",
            "value": 900
        },
        {
            "group": "shadow",
            "name": "WORLD3D_SHADOW_BIAS",
            "min": 0,
            "max": 0.005,
            "step": 0.0001,
            "kind": "number",
            "options": null,
            "label": "Depth bias",
            "value": 0.001
        },
        {
            "group": "shadow",
            "name": "WORLD3D_SHADOW_NORMAL_BIAS",
            "min": 0,
            "max": 4,
            "step": 0.1,
            "kind": "number",
            "options": null,
            "label": "Normal bias (texels)",
            "value": 0.8
        },
        {
            "group": "sky",
            "name": "WORLD3D_SKY_COLOR",
            "min": null,
            "max": null,
            "step": null,
            "kind": "color",
            "options": null,
            "label": "Sky and fog color",
            "value": 9421792
        },
        {
            "group": "sky",
            "name": "WORLD3D_FOG_DENSITY",
            "min": 0,
            "max": 0.002,
            "step": 0.00005,
            "kind": "number",
            "options": null,
            "label": "Fog",
            "value": 0.00014
        },
        {
            "group": "materials",
            "name": "WORLD3D_GROUND_SPECULAR",
            "min": 0,
            "max": 0.5,
            "step": 0.01,
            "kind": "number",
            "options": null,
            "label": "Ground specular",
            "value": 0
        },
        {
            "group": "materials",
            "name": "WORLD3D_GROUND_SPEC_POWER",
            "min": 1,
            "max": 128,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Ground specular size",
            "value": 1
        },
        {
            "group": "materials",
            "name": "WORLD3D_OUTER_TINT",
            "min": 0.3,
            "max": 1.3,
            "step": 0.02,
            "kind": "number",
            "options": null,
            "label": "Ground brightness beyond the location",
            "value": 0.85
        },
        {
            "group": "materials",
            "name": "WORLD3D_PROP_SPECULAR",
            "min": 0,
            "max": 1,
            "step": 0.01,
            "kind": "number",
            "options": null,
            "label": "Environment specular",
            "value": 0.04
        },
        {
            "group": "materials",
            "name": "WORLD3D_PROP_SPEC_POWER",
            "min": 1,
            "max": 128,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Environment specular size",
            "value": 9
        },
        {
            "group": "materials",
            "name": "WORLD3D_ACTOR_SPECULAR",
            "min": 0,
            "max": 1,
            "step": 0.01,
            "kind": "number",
            "options": null,
            "label": "Main object specular",
            "value": 0
        },
        {
            "group": "materials",
            "name": "WORLD3D_ACTOR_SPEC_POWER",
            "min": 1,
            "max": 128,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Main object specular size",
            "value": 23
        },
        {
            "group": "location",
            "name": "LOCATION_WIDTH",
            "min": 256,
            "max": 8192,
            "step": 64,
            "kind": "number",
            "options": null,
            "label": "Location width (px)",
            "value": 2048
        },
        {
            "group": "location",
            "name": "LOCATION_HEIGHT",
            "min": 256,
            "max": 8192,
            "step": 64,
            "kind": "number",
            "options": null,
            "label": "Location height (px)",
            "value": 2048
        },
        {
            "group": "location",
            "name": "LOCATION_GROUND",
            "min": null,
            "max": null,
            "step": null,
            "kind": "select",
            "options": [
                {
                    "value": 0,
                    "label": "grass"
                },
                {
                    "value": 1,
                    "label": "sand"
                },
                {
                    "value": 2,
                    "label": "snow"
                }
            ],
            "label": "Ground texture",
            "value": 0
        },
        {
            "group": "location",
            "name": "GROUND_TILE_SIZE",
            "min": 64,
            "max": 2048,
            "step": 16,
            "kind": "number",
            "options": null,
            "label": "Texture tile (px)",
            "value": 512
        },
        {
            "group": "location",
            "name": "TERRAIN_NOISE_AMP",
            "min": 0,
            "max": 200,
            "step": 2,
            "kind": "number",
            "options": null,
            "label": "Hill height (px)",
            "value": 44
        },
        {
            "group": "location",
            "name": "TERRAIN_NOISE_SCALE",
            "min": 60,
            "max": 3000,
            "step": 20,
            "kind": "number",
            "options": null,
            "label": "Hill size (px)",
            "value": 620
        },
        {
            "group": "location",
            "name": "TERRAIN_NOISE_SEED",
            "min": 0,
            "max": 99999,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Terrain seed",
            "value": 4
        },
        {
            "group": "location",
            "name": "TERRAIN_BASE",
            "min": -200,
            "max": 200,
            "step": 2,
            "kind": "number",
            "options": null,
            "label": "Ground level (px)",
            "value": 0
        },
        {
            "group": "location",
            "name": "TERRAIN_CELL",
            "min": 4,
            "max": 64,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Grid cell (px)",
            "value": 8
        },
        {
            "group": "models",
            "name": "MODEL_CLIP_BLEND_SEC",
            "min": 0,
            "max": 1,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Clip cross-fade (s)",
            "value": 0.2
        },
        {
            "group": "models",
            "name": "UI_REF_HEIGHT",
            "min": 0,
            "max": 2160,
            "step": 10,
            "kind": "number",
            "options": null,
            "label": "UI reference height (px)",
            "value": 720
        },
        {
            "group": "models",
            "name": "GAME_RUN_SEC",
            "min": 1,
            "max": 60,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Sample game: run time (s)",
            "value": 8
        },
        {
            "group": "models",
            "name": "GAME_REST_SEC",
            "min": 1,
            "max": 60,
            "step": 1,
            "kind": "number",
            "options": null,
            "label": "Sample game: rest time (s)",
            "value": 4
        },
        {
            "group": "models",
            "name": "GAME_STEP_SEC",
            "min": 0.1,
            "max": 2,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Sample game: step interval (s)",
            "value": 0.35
        },
        {
            "group": "audio-mixer",
            "name": "AUDIO_MASTER_VOLUME",
            "min": 0,
            "max": 1,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Master volume",
            "value": 0.85
        },
        {
            "group": "audio-mixer",
            "name": "AUDIO_MUSIC_VOLUME",
            "min": 0,
            "max": 1,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Music",
            "value": 0.45
        },
        {
            "group": "audio-mixer",
            "name": "AUDIO_SFX_VOLUME",
            "min": 0,
            "max": 1,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Effects",
            "value": 0.9
        },
        {
            "group": "audio-space",
            "name": "AUDIO_FALLOFF_MIN",
            "min": 0,
            "max": 2000,
            "step": 10,
            "kind": "number",
            "options": null,
            "label": "Falloff Min (px)",
            "value": 120
        },
        {
            "group": "audio-space",
            "name": "AUDIO_FALLOFF_MAX",
            "min": 100,
            "max": 8000,
            "step": 50,
            "kind": "number",
            "options": null,
            "label": "Falloff Max (px)",
            "value": 1150
        },
        {
            "group": "audio-space",
            "name": "AUDIO_PAN",
            "min": 0,
            "max": 1,
            "step": 0.05,
            "kind": "number",
            "options": null,
            "label": "Stereo width",
            "value": 0.75
        }
    ],
    "object": {
        "fields": {
            "name": {
                "type": "string",
                "required": true,
                "note": "unique among location objects"
            },
            "model": {
                "type": "string",
                "required": true,
                "note": "literal quoted path from the game root (assets/models/*.fbx or *.glb; unquoted here so the asset scanner skips the manifest)"
            },
            "kind": {
                "type": "string",
                "required": true,
                "enum": [
                    "prop",
                    "actor"
                ],
                "note": "actor — main objects of the frame, prop — environment"
            },
            "x": {
                "type": "number",
                "required": true,
                "note": "map px, right"
            },
            "y": {
                "type": "number",
                "required": true,
                "note": "map px, down"
            },
            "h": {
                "type": "number",
                "required": true,
                "note": "px above the ground"
            },
            "rot": {
                "type": "number[3]",
                "required": true,
                "note": "degrees [tilt-x, heading, tilt-z]; heading 0 — along +x, 90 — down the map"
            },
            "scale": {
                "type": "number[3]",
                "required": true,
                "note": "per axis, > 0 (1 cm in the file = 1 px)"
            },
            "anim": {
                "type": "object",
                "required": false,
                "note": "FBX part spin: { part, axis: 'x'|'-x'|'y'|… , speed: rpm, dir: 'cw'|'ccw' }"
            },
            "clip": {
                "type": "string",
                "required": false,
                "note": "looped GLB animation clip (idle, run…); none — rest pose"
            }
        }
    },
    "ui": {
        "kinds": {
            "text": {
                "anchor": "top-left",
                "x": 20,
                "y": 20,
                "text": "Text",
                "fontSize": 24,
                "color": "#ffffff",
                "shadow": "#000000",
                "alpha": 1,
                "visible": 1
            },
            "panel": {
                "anchor": "top-left",
                "x": 20,
                "y": 20,
                "w": 240,
                "h": 80,
                "fill": "#10202c",
                "border": "",
                "radius": 10,
                "alpha": 0.7,
                "visible": 1
            },
            "bar": {
                "anchor": "top-left",
                "x": 20,
                "y": 20,
                "w": 240,
                "h": 18,
                "value": 0.6,
                "color": "#5ad05a",
                "fill": "#10202c",
                "border": "#ffffff",
                "radius": 9,
                "alpha": 1,
                "visible": 1
            },
            "button": {
                "anchor": "bottom-center",
                "x": 0,
                "y": 40,
                "w": 180,
                "h": 48,
                "text": "Button",
                "fontSize": 20,
                "color": "#ffffff",
                "fill": "#2a6fb0",
                "border": "",
                "radius": 10,
                "alpha": 1,
                "visible": 1
            }
        },
        "anchors": [
            "top-left",
            "top-center",
            "top-right",
            "middle-left",
            "middle-center",
            "middle-right",
            "bottom-left",
            "bottom-center",
            "bottom-right"
        ]
    },
    "api": {
        "spawn": "Scene.spawn(model, opts) -> handle { name, def, loaded } ; opts: { name?, kind?, x?, y?, h?, heading?, rot?, scale?, clip? }",
        "move": "Scene.move(name, patch) -> handle ; patch fields of def (x, y, h, heading, rot, scale, clip, kind)",
        "remove": "Scene.remove(name) -> boolean",
        "query": "Scene.query(filter?) -> plain JSON snapshots [{ name, model, kind, x, y, h, rot, scale, clip, loaded, error }]",
        "inspect": "Scene.inspect() -> Promise<{ objects, loaded, errors, triangles, fps, findings }>",
        "follow": "Scene.follow(name | null) -> camera follows the object each frame",
        "manifest": "Scene.manifest() -> this schema (SCENE_SCHEMA)"
    }
};
