// The layer contract of the unified visual pipeline (the kit's API gate, extended):
//
//   js/core/ + js/presentation/ + js/profiles/ + js/Game.js  — the semantic layer:
//       no pc.*, no engine file imports, no `if (profile === …)` inside gameplay.
//   js/engine/ — the only place that knows PlayCanvas.
//
// Plus the machine-readable contracts: manifest/render-profiles.json validates, the
// generated files match it, and every profile in the manifest has exactly one adapter.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';
import { ROOT, loadScripts } from './browser-scripts.mjs';
import { loadManifest, validate } from '../tools/render-profiles.mjs';

const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');

const SEMANTIC = [];
for (const dir of ['js/core', 'js/presentation', 'js/profiles']) {
    const walk = (d) => {
        for (const e of fs.readdirSync(path.join(ROOT, d), { withFileTypes: true })) {
            const full = path.join(d, e.name);
            if (e.isDirectory()) walk(full);
            else if (e.name.endsWith('.js')) SEMANTIC.push(full.split(path.sep).join('/'));
        }
    };
    walk(dir);
}
SEMANTIC.push('js/Game.js', 'js/GameSpec.js');

test('semantic layer never touches pc.* (the engine does)', () => {
    for (const rel of SEMANTIC) {
        const hits = read(rel).split('\n')
            .map((l) => l.replace(/\/\/.*$/, ''))           // comments may name pc.*
            .map((l, i) => [i + 1, l]).filter(([, l]) => /\bpc\./.test(l));
        assert.deepEqual(hits, [], rel + ': строки с pc.: ' + hits.map(h => h[0]).join(','));
    }
});

test('gameplay never branches on the render profile (no renderer checks in the game)', () => {
    // comments may explain the rule; the code must follow it
    const src = read('js/Game.js').split('\n').map(l => l.replace(/\/\/.*$/, '')).join('\n');
    for (const bad of ['RenderProfile.id() ===', "profile === '2d'", 'projection ===', 'pc.', 'Model3D.', 'Sprite2D.', 'World3D.']) {
        assert.ok(!src.includes(bad), 'js/Game.js references ' + bad + ' — gameplay must stay renderer-independent');
    }
});

test('every engine adapter lives in js/engine and is the only user of the kit 3D APIs there', () => {
    for (const rel of ['js/engine/Visual3D.js', 'js/engine/Sprite2D.js', 'js/engine/Camera3D.js', 'js/engine/Lighting3D.js']) {
        assert.ok(fs.existsSync(path.join(ROOT, rel)), rel);
        assert.match(read(rel), /\bpc\.|World3D|Model3D|Procedural3D|CameraController/, rel + ' must be an engine adapter');
    }
});

test('manifest/render-profiles.json validates and generates what the runtime reads', () => {
    const m = loadManifest(ROOT);
    assert.deepEqual(validate(m), [], 'the manifest must validate');
    assert.deepEqual(m.order, ['2d', '2.5d', 'isometric3d', 'lowpoly3d', 'full3d']);
    const generated = read('js/presentation/RenderProfiles.js');
    assert.match(generated, /GENERATED by tools\/render-profiles\.mjs/);
    for (const id of m.order) {
        assert.ok(generated.includes('"' + id + '"'));
        // one adapter per profile, and it registers exactly that id
        const adapter = read('js/profiles/' + id + '/profile.js');
        assert.match(adapter, new RegExp("ArcProfiles\\.define\\(\\{\\s*\\n\\s*id: '" + id + "'"));
        // a per-profile canon file exists for agents and the editor
        const perProfile = JSON.parse(read('presentation/profiles/' + id + '.json'));
        assert.equal(perProfile.id, id);
        assert.equal(perProfile.projection, m.profiles[id].projection);
    }
    // the migration contract: preserve/change/steps are machine-readable
    assert.ok(m.migration.preserve.includes('entity_ids'));
    assert.ok(m.migration.preserve.includes('save_schema'));
    assert.ok(m.migration.change.includes('visual_assets'));
    assert.ok(m.migration.steps.includes('snapshot'));
    assert.ok(m.migration.steps.includes('commit'));
    assert.equal(m.migration.nonDestructive, true);
});

test('the project descriptor and the variant files agree (one Master Project)', () => {
    const project = JSON.parse(read('project.json'));
    const variants = fs.readdirSync(path.join(ROOT, 'presentation/variants')).filter(f => f.endsWith('.json'));
    assert.equal(project.variants.length, variants.length);
    for (const id of project.variants) {
        const v = JSON.parse(read('presentation/variants/' + id + '.json'));
        assert.equal(v.id, id);
        assert.ok(project.profiles.includes(v.profile), id + ' references a canonical profile');
        assert.ok(project.variantFiles[id]);
    }
    assert.ok(project.variants.includes(project.defaultVariant));
    assert.equal(project.gameModel, 'js/GameSpec.js', 'one shared game model for every variant');
});

test('putInLayer: прозрачный инстанс принудительно пере-добавляется в слой (кворк движка)', () => {
  // A fake layer bookkeeping: record add/remove calls; the guard must double-add transparens.
  const calls = [];
  const layer = { addMeshInstances: (list) => calls.push(['add', list.length]), removeMeshInstances: (list) => calls.push(['rm', list.length]) };
  const view = {
    app: { scene: { layers: { getLayerById: () => layer } } },
    _miLayers: new Map(),
  };
  // The method lives on View3D: load the engine file in a vm context and take the prototype.
  const enginePage = loadScripts(['js/Constants.js', 'js/engine/World3D.js'], { pc: { BLEND_NONE: 0, BLEND_PREMULTIPLIED: 3 } });
  const proto = enginePage.get('View3D').prototype;
  const transparent = { material: { blendType: 3 } };   // pc.BLEND_PREMULTIPLIED-ish
  const opaque = { material: { blendType: 0 } };
  proto.putInLayer.call(view, transparent, 7);
  assert.deepEqual(calls, [['add', 1], ['rm', 1], ['add', 1]], 'прозрачный: add → rm → add');
  calls.length = 0;
  proto.putInLayer.call(view, transparent, 7);
  assert.deepEqual(calls, [], 'тот же инстанс в тот же слой повторно: ничего не делаем');
  const view2 = { app: { scene: { layers: { getLayerById: () => layer } } }, _miLayers: new Map() };
  proto.putInLayer.call(view2, opaque, 7);
  assert.deepEqual(calls, [['add', 1]], 'непрозрачный: одно добавление');
});
