// Variants.js — GENERATED by tools/variants.mjs — do not edit by hand.
// The Master Project and its visual variants as the runtime reads them (no fetch, no build
// step). Canon: js/GameSpec.js (the shared game model) + presentation/variants/*.json (one
// file per variant) + presentation/mappings/*.json + presentation/presets/*.json.
// A variant is CONFIGURATION, never a copy: every entry presents the same GAME_SPEC.
/** @satisfies {Record<string, any>} */
const PROJECT_VARIANTS = {
    "project": {
        "id": "wanderburg",
        "name": "Wanderburg",
        "kit": "ArcEngine",
        "version": "1.1.0",
        "schemaVersion": 1,
        "defaultVariant": "wanderburg-lowpoly3d",
        "profiles": [
            "2d",
            "2.5d",
            "isometric3d",
            "lowpoly3d",
            "full3d"
        ],
        "variants": [
            "wanderburg-2.5d",
            "wanderburg-2d",
            "wanderburg-full3d",
            "wanderburg-isometric3d",
            "wanderburg-lowpoly3d"
        ],
        "variantFiles": {
            "wanderburg-2.5d": "presentation/variants/wanderburg-2.5d.json",
            "wanderburg-2d": "presentation/variants/wanderburg-2d.json",
            "wanderburg-full3d": "presentation/variants/wanderburg-full3d.json",
            "wanderburg-isometric3d": "presentation/variants/wanderburg-isometric3d.json",
            "wanderburg-lowpoly3d": "presentation/variants/wanderburg-lowpoly3d.json"
        },
        "gameModel": "js/GameSpec.js",
        "assetRegistry": "GAME_SPEC.assets + presentation/mappings/*.json",
        "runtime": {
            "entry": "js/presentation/Runtime.js (PlayArcRuntime.start)",
            "url": "/?project=wanderburg&variant=<variantId>",
            "cli": "node tools/arc.mjs run --variant <variantId>",
            "all": "node tools/arc.mjs run --all"
        },
        "shared": {
            "gameplay": "ONE Game Model for every variant: rules, systems, world, entities, progression, save schema",
            "entityIds": [
                "castle",
                "warden-gate"
            ],
            "scenes": [
                "gameplay",
                "boss",
                "main-menu",
                "loadout",
                "legacy",
                "draft",
                "pause",
                "settings",
                "help",
                "run-over"
            ]
        },
        "generated": "tools/variants.mjs from js/GameSpec.js + presentation/variants/*.json"
    },
    "variants": {
        "wanderburg-2.5d": {
            "id": "wanderburg-2.5d",
            "name": "Wanderburg — Hybrid 2.5D",
            "profile": "2.5d",
            "enabled": true,
            "description": "CONVERSION TARGET. An orthographic top-down lens with the shading model switched off (the flat preset: no toon bands, no ink; sun and sky still come from the biome). The world stays the 3D height field — see environment — so what this shows today is the valley from directly above, not sprite art: a real 2.5D presentation needs billboard sprites for the roles in GAME_SPEC.assets (skill asset-representation, tools/placeholder.mjs). Every entity is SELF-PRESENTED (GAME_SPEC.entities declare representation \"none\"): js/WanderView.js + js/WanderMesh.js build the meshes on the kit engine layer, so the pipeline binds no second copy of anything.",
            "createdBy": "author",
            "createdFrom": "wanderburg-lowpoly3d",
            "camera": {
                "mode": "topdown",
                "follow": null,
                "azimuthDeg": -90,
                "elevationDeg": 88,
                "orthoHeightPx": 540,
                "zoomMin": 0.4,
                "zoomMax": 1.7,
                "orbit": false
            },
            "lighting": {
                "preset": "flat",
                "shadows": 0,
                "toon": 0,
                "ink": 0,
                "outline": 0
            },
            "materials": {
                "shading": "unlit",
                "ink": 0,
                "outline": 0
            },
            "environment": {
                "ground": "terrain",
                "flatten": 0,
                "tilePx": 64
            },
            "animation": {
                "style": "sprite-frames"
            },
            "ui": {
                "space": "screen",
                "scale": 1
            },
            "audio": {
                "spatial": false
            },
            "effects": {
                "particles": 160,
                "postprocessing": "none"
            },
            "performance": {
                "maxDrawCalls": 300,
                "maxParticles": 160,
                "maxShadowLights": 0
            }
        },
        "wanderburg-2d": {
            "id": "wanderburg-2d",
            "name": "Wanderburg — Pixel 2D",
            "profile": "2d",
            "enabled": true,
            "description": "CONVERSION TARGET, the furthest from what ships: orthographic, flat, declarative depth. Wanderburg has no sprite art at all — every mesh is built in code — so this variant documents the migration end point: the roles in GAME_SPEC.assets resolve to GENERATED placeholders until real sprites exist (`arc variant convert --source wanderburg-lowpoly3d --profile 2d --write-placeholders` materializes them). Gameplay, entity ids and the save schema are identical to every other variant. Every entity is SELF-PRESENTED (GAME_SPEC.entities declare representation \"none\"): js/WanderView.js + js/WanderMesh.js build the meshes on the kit engine layer, so the pipeline binds no second copy of anything.",
            "createdBy": "author",
            "createdFrom": "wanderburg-2.5d",
            "camera": {
                "mode": "topdown",
                "follow": null,
                "azimuthDeg": -90,
                "elevationDeg": 88,
                "orthoHeightPx": 480,
                "zoomMin": 0.4,
                "zoomMax": 1.7,
                "orbit": false
            },
            "lighting": {
                "preset": "flat",
                "shadows": 0,
                "toon": 0,
                "ink": 0,
                "outline": 0
            },
            "materials": {
                "shading": "unlit",
                "ink": 0,
                "outline": 0
            },
            "environment": {
                "ground": "terrain",
                "flatten": 0,
                "tilePx": 64
            },
            "animation": {
                "style": "sprite-frames"
            },
            "ui": {
                "space": "screen",
                "scale": 1
            },
            "audio": {
                "spatial": false
            },
            "effects": {
                "particles": 120,
                "postprocessing": "none"
            },
            "performance": {
                "maxDrawCalls": 260,
                "maxParticles": 120,
                "maxShadowLights": 0
            }
        },
        "wanderburg-full3d": {
            "id": "wanderburg-full3d",
            "name": "Wanderburg — Cinematic 3D",
            "profile": "full3d",
            "enabled": true,
            "description": "The full stack over the same meshes: perspective camera lower on the horizon, smooth (non-banded) shading, a real shadow map, denser fog. Heavier than the shipped look — the materials are authored for toon bands — so this variant is a mood experiment and a migration target rather than a release candidate. Every entity is SELF-PRESENTED (GAME_SPEC.entities declare representation \"none\"): js/WanderView.js + js/WanderMesh.js build the meshes on the kit engine layer, so the pipeline binds no second copy of anything.",
            "createdBy": "author",
            "createdFrom": "wanderburg-lowpoly3d",
            "camera": {
                "mode": "thirdPerson",
                "follow": null,
                "azimuthDeg": -90,
                "elevationDeg": 32,
                "fovDeg": 55,
                "zoomMin": 0.4,
                "zoomMax": 1.7,
                "orbit": true
            },
            "lighting": {
                "preset": "realistic",
                "shadows": 1,
                "toon": 0,
                "ink": 0,
                "outline": 0
            },
            "materials": {
                "shading": "pbr",
                "ink": 0,
                "outline": 0
            },
            "environment": {
                "ground": "terrain",
                "flatten": 0,
                "tilePx": 64
            },
            "animation": {
                "style": "procedural-parts"
            },
            "ui": {
                "space": "screen",
                "scale": 1
            },
            "audio": {
                "spatial": true
            },
            "effects": {
                "particles": 240,
                "postprocessing": "stylized"
            }
        },
        "wanderburg-isometric3d": {
            "id": "wanderburg-isometric3d",
            "name": "Wanderburg — Isometric 3D",
            "profile": "isometric3d",
            "enabled": true,
            "description": "The same valley through a parameterized ORTHOGRAPHIC lens: a fixed 45° azimuth and elevation, no perspective foreshortening, the mountain ring reads as a clean circle. A working alternative look, not a migration target — meshes, toon bands and ink edges are unchanged; only the projection and the framing differ. Every entity is SELF-PRESENTED (GAME_SPEC.entities declare representation \"none\"): js/WanderView.js + js/WanderMesh.js build the meshes on the kit engine layer, so the pipeline binds no second copy of anything.",
            "createdBy": "author",
            "createdFrom": "wanderburg-lowpoly3d",
            "camera": {
                "mode": "isometric",
                "follow": null,
                "azimuthDeg": -45,
                "elevationDeg": 45,
                "orthoHeightPx": 620,
                "zoomMin": 0.4,
                "zoomMax": 1.7,
                "orbit": false
            },
            "lighting": {
                "preset": "isometric",
                "shadows": 0,
                "toon": 1,
                "ink": 2,
                "outline": 0
            },
            "materials": {
                "shading": "toon",
                "ink": 2,
                "outline": 0
            },
            "environment": {
                "ground": "terrain",
                "flatten": 0,
                "tilePx": 64
            },
            "animation": {
                "style": "procedural-parts"
            },
            "ui": {
                "space": "screen",
                "scale": 1
            },
            "audio": {
                "spatial": true
            },
            "effects": {
                "particles": 240,
                "postprocessing": "none"
            },
            "performance": {
                "maxParticles": 240,
                "maxShadowLights": 0
            }
        },
        "wanderburg-lowpoly3d": {
            "id": "wanderburg-lowpoly3d",
            "name": "Wanderburg — Low-poly 3D (shipped)",
            "profile": "lowpoly3d",
            "enabled": true,
            "description": "THE presentation the game ships: a perspective camera over the rolling fortress, hand-built low-poly meshes, toon bands with environment ink edges, no silhouette outline (on convex hand-built meshes the inverted hull wins the depth tie and paints the object black), no shadow map — every hull drops its own blob shadow. Sun, sky and fog come from the biome (js/Content.js), so the variant pins only the shading model. Camera pose and the zoom range mirror Constants.js (CAMERA_*); the zoom itself stays authored by the game (CAMERA_ZOOM / CAMERA_ZOOM_MOBILE). Draw load, measured on a full valley (verify/deploy.mjs, C-6): ~900 unique enabled mesh instances and 4-8k GL draws per frame (scene-dependent), because WORLD3D_TOON_INK=2 renders an ink-edge pass over the world; maxDrawCalls therefore states the profile canon (900 instances), not a wish — a mobile build halves the draw count with WORLD3D_TOON_INK=0 or 1. Every entity is SELF-PRESENTED (GAME_SPEC.entities declare representation \"none\"): js/WanderView.js + js/WanderMesh.js build the meshes on the kit engine layer, so the pipeline binds no second copy of anything.",
            "createdBy": "author",
            "createdFrom": null,
            "camera": {
                "mode": "thirdPerson",
                "follow": null,
                "azimuthDeg": -90,
                "elevationDeg": 55,
                "fovDeg": 52,
                "zoomMin": 0.4,
                "zoomMax": 1.7,
                "orbit": true
            },
            "lighting": {
                "preset": "lowpoly",
                "shadows": 0,
                "toon": 1,
                "ink": 2,
                "outline": 0
            },
            "materials": {
                "shading": "toon",
                "ink": 2,
                "outline": 0
            },
            "environment": {
                "ground": "terrain",
                "flatten": 0,
                "tilePx": 64
            },
            "animation": {
                "style": "procedural-parts"
            },
            "ui": {
                "space": "screen",
                "scale": 1
            },
            "audio": {
                "spatial": true
            },
            "effects": {
                "particles": 240,
                "postprocessing": "none"
            },
            "performance": {
                "maxDrawCalls": 900,
                "maxParticles": 240,
                "maxShadowLights": 0
            }
        }
    },
    "mappings": {},
    "presets": {
        "cinematic": {
            "id": "cinematic",
            "description": "A reusable over-the-shoulder look: lower camera, longer lens feel, realistic light, a little fog.",
            "camera": {
                "mode": "thirdPerson",
                "elevationDeg": 12,
                "distance": 520,
                "fovDeg": 46
            },
            "lighting": {
                "preset": "realistic",
                "fog": 0.0004,
                "sunIntensity": 1.05,
                "shadows": 1,
                "toon": 0
            },
            "effects": {
                "postprocessing": "cinematic"
            }
        },
        "pixel-topdown": {
            "id": "pixel-topdown",
            "description": "A reusable pixel-art top-down look: straight-down orthographic camera, flat light, crisp sprites.",
            "camera": {
                "mode": "topdown",
                "elevationDeg": 88,
                "orthoHeightPx": 360,
                "orbit": false
            },
            "lighting": {
                "preset": "flat",
                "shadows": 0,
                "toon": 0,
                "ink": 0,
                "outline": 0,
                "fog": 0
            },
            "environment": {
                "ground": "tilemap",
                "flatten": 1
            }
        }
    },
    "journal": []
};
