// ============================================================================
//  ArcEngine — agent skills sync
// ----------------------------------------------------------------------------
//  node tools/sync-skills.mjs            regenerate the agent-facing copies
//  node tools/sync-skills.mjs --check    fail if the copies differ from the canon
//
//  Canon (hand-edited, dot-free paths — they reach web-upload users):
//    claude/skills/<name>/…          the kit's own skills
//    claude/vendor/playcanvas/<name>/…   vendored @playcanvas/skills (MIT, v0.3.0)
//
//  Generated (committed, never hand-edited; agents discover them natively):
//    .claude/skills/<name>/…         Claude Code (Skill tool)
//    .agents/skills/<name>/…         Codex / Cursor / Agent Skills convention
//    .cursor/rules/arcengine.mdc     Cursor rule with the kit's invariants
//    AGENTS.md                       cross-agent entry point
//
//  The generated tree is exactly the canon tree per skill folder (byte-for-byte),
//  plus the four entry files above. check.mjs runs --check on every verification.
// ============================================================================
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import vm from 'node:vm';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const GEN_MARK = '<!-- GENERATED by tools/sync-skills.mjs — edit the canon (claude/skills/, claude/vendor/), not this file. -->';

const CANON_DIRS = [
    { root: 'claude/skills', origin: 'kit' },
    { root: 'claude/vendor/playcanvas', origin: 'playcanvas' }
];

const fail = (msg) => { console.error('  ' + msg); process.exitCode = 1; };

// --- collect the canon -------------------------------------------------------
/** @type {Map<string, { origin: string, dir: string }>} */
const skills = new Map();
for (const { root, origin } of CANON_DIRS) {
    const abs = path.join(ROOT, root);
    if (!fs.existsSync(abs)) continue;
    for (const e of fs.readdirSync(abs, { withFileTypes: true })) {
        if (!e.isDirectory()) continue;
        const skillMd = path.join(abs, e.name, 'SKILL.md');
        if (!fs.existsSync(skillMd)) continue;
        if (skills.has(e.name)) fail('collision: skill "' + e.name + '" exists in both the kit canon and the vendor');
        skills.set(e.name, { origin, dir: path.join(root, e.name) });
    }
}
if (!skills.size) { fail('no skills found in the canon'); process.exit(1); }

const descriptionOf = (rel) => {
    const head = fs.readFileSync(path.join(ROOT, rel, 'SKILL.md'), 'utf8').match(/^---\n([\s\S]*?)\n---\n/);
    const m = head && head[1].match(/^description: ([\s\S]*?)$/m);
    return m ? m[1].replace(/\s*\n\s*/g, ' ').trim() : '';
};

// --- expected generated content ----------------------------------------------
const walk = (rel) => fs.readdirSync(path.join(ROOT, rel), { withFileTypes: true }).flatMap(e =>
    e.isDirectory() ? walk(path.join(rel, e.name)) : [path.join(rel, e.name)]);

/** @type {Map<string, string>} rel path (posix) -> expected content */
const expected = new Map();
for (const [name, { dir }] of [...skills].sort()) {
    for (const file of walk(dir)) {
        const rel = path.relative(dir, path.join(ROOT, file)).split(path.sep).join('/');
        for (const target of ['.claude/skills', '.agents/skills']) {
            expected.set(target + '/' + name + '/' + rel, fs.readFileSync(path.join(ROOT, file), 'utf8'));
        }
    }
}

// scene contract versions (js/SceneSchema.js is generated by tools/manifest.mjs)
const schemaFile = path.join(ROOT, 'js', 'SceneSchema.js');
let schemaVersion = 0, gameVersion = '0.0.0';
if (fs.existsSync(schemaFile)) {
    const ctx = vm.createContext({});
    vm.runInContext(fs.readFileSync(schemaFile, 'utf8'), ctx);
    const sc = vm.runInContext('SCENE_SCHEMA', ctx);
    schemaVersion = sc.schemaVersion;
    gameVersion = sc.gameVersion;
}

const kitSkills = [...skills].filter(([, s]) => s.origin === 'kit').map(([n]) => n).sort();
const vendorSkills = [...skills].filter(([, s]) => s.origin === 'playcanvas').map(([n]) => n).sort();

expected.set('AGENTS.md', `${GEN_MARK}
# ArcEngine — agent entry point

ArcEngine is a zero-dependency kit for 3D browser games on PlayCanvas 2 (vanilla JS,
classic \`<script>\` tags, no npm, no build step). Humans: \`CLAUDE.md\` and \`README.md\`.
Strategy: \`ROADMAP.md\`.

## Work protocol

1. Before editing an area, read the matching skill: \`<name>\` lives in
   \`.agents/skills/<name>/SKILL.md\` (same text as the canon \`claude/skills/<name>/SKILL.md\`).
   Vendored PlayCanvas engine skills sit alongside under their own names.
2. Keep the invariants (full list in \`CLAUDE.md\`): zero dependencies; script order in
   \`index.html\`; every number in \`Constants.js\`; 3D is a view (game logic never asks the
   renderer for heights or intersections); world objects through \`World3D.addObject\`;
   HUD only through \`UILayout.js\` + \`UI.get(id)\`; the map space is right-handed while the
   engine world is its X mirror (skill \`world3d\`, §Coordinates).
3. Verify before handing over: \`node tools/check.mjs\` (types, tests, skills sync) and,
   for geometry/material/light/shader edits, \`await Debug3D.lint()\` in the running game.
4. Skills and code comments are English; user-facing strings may be Russian.

## Skills map

| Skill | Use before |
|---|---|
${kitSkills.map(n => `| \`${n}\` | ${descriptionOf(skills.get(n).dir).slice(0, 160)} |`).join('\n')}

Vendored PlayCanvas engine skills (MIT, v0.3.0): ${vendorSkills.map(n => '`' + n + '`').join(', ')} —
engine-level workflows (effects, shader chunks, glb inspection, pixel verification);
the kit's own skills win on any conflict about kit files.

## Generated copies

\`.claude/skills/\`, \`.agents/skills/\`, \`.cursor/rules/arcengine.mdc\` and this file are
regenerated by \`node tools/sync-skills.mjs\` from the canon; \`check.mjs\` fails when they drift.
`);

expected.set('agent-manifest.json', JSON.stringify({
    kit: 'ArcEngine',
    gameVersion,
    apiVersion: { scene: schemaVersion, manifest: 1 },
    engine: 'PlayCanvas 2 (libs/playcanvas.min.js, WebGL2 only)',
    license: 'MIT (see LICENSE, NOTICE)',
    entryPoints: {
        human: ['README.md', 'CLAUDE.md', 'ROADMAP.md'],
        agents: ['AGENTS.md', 'agent-manifest.json', '.agents/skills/', '.claude/skills/', '.cursor/rules/arcengine.mdc']
    },
    skills: {
        kit: kitSkills.map(n => ({ name: n, description: descriptionOf(skills.get(n).dir).slice(0, 200), canon: 'claude/skills/' + n + '/SKILL.md' })),
        vendor: { source: '@playcanvas/skills', version: 'v0.3.0', license: 'MIT', names: vendorSkills },
        priority: 'kit skills win over vendor on any conflict about kit files'
    },
    api: {
        scene: ['spawn(model, opts)', 'move(name, patch)', 'remove(name)', 'query(filter?)', 'inspect()', 'follow(name|null)', 'manifest()', 'seed(n)', 'random()', 'journal()'],
        edit: ['Edit.begin(label)', 'tx.add(model, opts)', 'tx.update(name, patch)', 'tx.remove(name)', 'tx.ops()', 'tx.commit()', 'tx.rollback()'],
        ui: ['UI.get(id)', 'UI.query()', 'UI.patch(id, patch)', 'UI.add(def)', 'UI.remove(id)'],
        kit: ['Kit.state(key, value?)', 'Kit.onFrame(name, fn)', 'Kit.offFrame(name)', 'Kit.time()', 'Kit.dt()', 'Kit.fps()'],
        asset: ['Asset.preload(path)', 'Asset.list()', 'Asset.loaded(path)']
    },
    checks: {
        fast: 'node tools/check.mjs',
        release: 'node tools/check.mjs --all',
        types: 'node tools/check.mjs --types',
        tests: 'node tools/check.mjs --tests',
        skillsSync: 'node tools/sync-skills.mjs --check',
        sceneManifest: 'node tools/manifest.mjs --check',
        render: 'node tools/headless-gate.mjs --render',
        visual: 'node tools/headless-gate.mjs --visual',
        serve: { game: 'node tools/dev-server.mjs', editor: 'node _utils/editor/server.mjs' },
        cli: {
            anyOs: 'node tools/arc.mjs <run|editor|check|build|gate|sync|manifest|scaffold>',
            windows: 'run.bat / editor.bat / check.bat / build.bat (thin wrappers)',
            unix: './run.sh / ./editor.sh / ./check.sh / ./build.sh (thin wrappers)'
        }
    },
    determinism: {
        agentPrng: 'Scene.seed(n) + Scene.random(); starters use Scene.random, never Math.random',
        terrain: 'TERRAIN_NOISE_SEED constant (editor-tunable), independent of Scene.seed',
        visualGate: 'fixed viewport 1280x720, fixed seed in the gate scenarios'
    }
}, null, 4) + '\n');

expected.set('.cursor/rules/arcengine.mdc', `---
description: ArcEngine kit invariants and skill map for AI agents
alwaysApply: true
---

${GEN_MARK}

ArcEngine: zero-dependency 3D browser-game kit on PlayCanvas 2 (vanilla JS, no npm/build).
Read \`AGENTS.md\` for the work protocol and \`CLAUDE.md\` for the full invariants.

- Before editing kit areas, read the matching skill in \`.agents/skills/<name>/SKILL.md\`:
  ${kitSkills.map(n => '`' + n + '`').join(', ')}.
- Engine-level PlayCanvas workflows: vendored skills ${vendorSkills.map(n => '`' + n + '`').join(', ')}.
- Never hand-edit generated copies (\`.claude/skills/\`, \`.agents/skills/\`, this rule,
  \`AGENTS.md\`): edit the canon (\`claude/skills/\`, \`claude/vendor/\`) and run
  \`node tools/sync-skills.mjs\`.
- Verify: \`node tools/check.mjs\`; rendered look — \`Debug3D.lint()\` / skill \`verify\`.
`);

// --- write or check -----------------------------------------------------------
const posix = (p) => p.split(path.sep).join('/');
let drift = 0;

const put = (rel, content) => {
    const abs = path.join(ROOT, rel);
    if (CHECK) {
        const have = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
        if (have !== content) { fail('drift: ' + rel); drift++; }
        return;
    }
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
};

if (!CHECK) {
    // regenerate from scratch: no stale files survive
    for (const target of ['.claude/skills', '.agents/skills']) {
        fs.rmSync(path.join(ROOT, target), { recursive: true, force: true });
    }
    for (const [rel, content] of expected) put(rel, content);
} else {
    for (const target of ['.claude/skills', '.agents/skills']) {
        const abs = path.join(ROOT, target);
        if (!fs.existsSync(abs)) continue;
        for (const file of walk(target)) {
            if (!expected.has(posix(file))) { fail('stale: ' + posix(file)); drift++; }
        }
    }
}

if (CHECK) {
    if (drift) {
        console.error('skills sync: ' + drift + ' file(s) drift — run node tools/sync-skills.mjs');
        process.exit(1);
    }
    console.log('skills sync: ok (' + skills.size + ' skills, ' + expected.size + ' generated files)');
} else {
    console.log('skills sync: ' + skills.size + ' skills -> .claude/skills, .agents/skills, .cursor/rules, AGENTS.md');
}
